apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: swipe-docs-prod
  name: swipe-docs-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - "swipeio.dev"
      secretName: swipeio-tls
  rules:
    - host: "swipeio.dev"
      http:
        paths:
          - pathType: Prefix
            path: "/?(.*)"
            backend:
              service:
                name: swipe-docs
                port:
                  number: 80
