name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build, push, and deploy

    env:
      IMAGE_TAG: prod-${{ github.sha }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: $GITHUB_WORKSPACE/node_modules
          key: ${{ runner.os }}-nodejs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nodejs-

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag registry.digitalocean.com/team127/swipe-docs:${IMAGE_TAG}

      - name: Login Docker Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push Image Registry
        run: docker push registry.digitalocean.com/team127/swipe-docs:${IMAGE_TAG}

      - name: Update Deployment File
        run: sed -i 's|<IMAGE_TAG>|'${IMAGE_TAG}'|' $GITHUB_WORKSPACE/k8s/overlays/prod/deployment.yaml

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s127team

      - name: Deploy To DigitalOcean Kubernetes
        run: kubectl apply -k $GITHUB_WORKSPACE/k8s/overlays/prod

      - name: Verify Deployment
        run: kubectl rollout status deployment/swipe-docs -n swipe-docs-prod
