name: CI PR

on:
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: $GITHUB_WORKSPACE/node_modules
          key: ${{ runner.os }}-nodejs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nodejs-

      - name: Build Docker Image
        run: TAG=$(echo $GITHUB_SHA | head -c7) && docker build . --file Dockerfile --tag registry.digitalocean.com/team127/swipe-docs:${TAG}

